### ISSUE TITLE
No more releases?

### ISSUE THREAD

**Issue by paresthesia69** [nohros/nsPopover#115]
Is this repo still maintained? I see that master and release 0.6.8 is noticeably different. I was wondering if we will see an updated release?

**Comment by nohros** [comment]
@paresthesia69 The repo is still maintained, however I don't have much time to check the changes that was performed by other members. Someone should need to do that and publish new releases.

Do you want to do it?

**Comment by paresthesia69** [comment]
Thanks for the offer. Unfortunately, I wouldn't have time to help the effort here and also maintain my current projects/work. Hopefully someone else can help out. Good luck and take care.
