### ISSUE TITLE
Officially maintained on npm?

### ISSUE THREAD

**Issue by kennynaoh** [nohros/nsPopover#116]
Hello @nohros ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
A question want to ask.
Is this library officially maintained on [npm](https://www.npmjs.com/package/ns-popover)?
Please help confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8350
https://github.com/cdnjs/cdnjs/pull/8362

**Comment by nohros** [comment]
Yes, it is.

**Comment by kennynaoh** [comment]
Thanks!
