### ISSUE TITLE
Could we directly use the source file

### ISSUE THREAD

**Issue by kennynaoh** [nohros/nsPopover#117]
Hello @nohros ,
I am the member of cdnjs project.
We want to host this library.
I have a question want to ask.
Could we directly use the source file?
Please help me confirm that.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8350
https://github.com/cdnjs/cdnjs/pull/8362

**Comment by itamark** [comment]
Hey @nohros - don't forget to respond to this :-)

**Comment by nohros** [comment]
@kennynaoh  Yes, you can.

**Comment by kennynaoh** [comment]
Thanks @nohros
