### ISSUE TITLE
Improve Closing Popover, Close trigger button?

### ISSUE THREAD

**Issue by michaelryancaputo** [nohros/nsPopover#2]
Would be great to improve the closing of the popover, maybe have it close on mouse out, or even add a close button.

**Comment by jjalonso** [comment]
What about if I want to disable the timeout? is possible?

**Comment by cristianoventura** [comment]
@jjalonso I don't know if you still need this... but `ns-popover-timeout="-1"` disable timeout.

**Comment by jjalonso** [comment]
Long time. But I'll consider it for next time. Thanks
