### ISSUE TITLE
Dynamically positioning the popover

### ISSUE THREAD

**Issue by bhuwan-arora** [nohros/nsPopover#5]
Hi
I want to dynamically position the popover to the other side if the popover is just at the boundary of the page and hence is getting hidden. Is there a way I can handle this issue? Please help. Thanks.

**Comment by noordawod** [comment]
@bhuwan-arora 
This is an ongoing issue and have been report here #1. I will close this issue and ask you to subscribe to nsPopover to know when we'll make this a reality, thanks a lot for bringing this matter to our attention.
